0.0.5-d7da Changes; 8 of 10 completed
- **TODO** Added `s3d-flow-finish`
- **TODO** Added `s3d-ssh` showing levels
- Added `part` output to `s3d-flow-json`
- Added `s3d-bash`
- Added checkout of detached head
- Added pre-release id incrementing
- Added push to `next`
- Changed most script names
- Improved `README.md`
- Replaced `LICENSE`

diff --git a/s3d-flow-check b/s3d-flow-check
--- a/s3d-flow-check
+++ b/s3d-flow-check
@@ -7,8 +7,8 @@ block=$(sed -e '/Next/,$d' < CHANGES.md | sed -n -e "/$v_/,\$p")
 block=$(echo "$block" | grep -v -E '^##')
 done=$(echo "$block" | grep -v -E '^- \*\*TODO\*\*' | wc -l)
 items=$(echo "$block" | grep -E '^-' | wc -l)
-commit=$"$v Changes; $done of $items completed"
-commit="$commit"$'\n\n';
-commit="$commit$block"
-git add -A
-git commit -m "$commit"
+
+if [[ done != items ]]; then
+  echo 'ERROR: not all items are done!' >&2
+  exit 1
+fi
