Shell check issues

diff --git a/s3d-flow-finish b/s3d-flow-finish
--- a/s3d-flow-finish
+++ b/s3d-flow-finish
@@ -1,7 +1,9 @@
 #!/bin/bash
+# shellcheck disable=SC1091
+# shellcheck disable=SC2001
 set -e
 
-n=1; p="$1"; name="$p";  [ -n "$p" ] || err="\$$n (message) is required"
+n=1; p="$1"; message="$p";  [ -n "$p" ] || err="\$$n (message) is required"
 
 [ -z "$err" ] || { {
   echo -e "ERR..: $err"
@@ -22,11 +24,11 @@ v2=$(s3d-flow-json | jq -r .release)
 if [[ "$v" == "$v2" ]]; then
   echo "FLOW: ALREADY FINISHED $S3D_MODULE?ref=$(git describe)"
 else
-  v_=$(echo $v | sed 's/\./\\\./')
-  v2_=$(echo $v2 | sed 's/\./\\\./')
+  v_=$(echo "$v" | sed 's/\./\\\./')
+  v2_=$(echo "$v2" | sed 's/\./\\\./')
   sed -i -e 's/\['"$v_"'\]/\['"$v2_"'\]/' CHANGES.md
   s3d-flow-reset
-  . s3d-flow "$1"
+  . s3d-flow "$message"
 fi
 
 echo "FLOW: FINISHED $S3D_MODULE?ref=$(git describe)"
