0.0.5-f4c6 Changes; 7 of 10 completed
- **TODO** Added `part` output to `s3d-flow-json`
- **TODO** Added `s3d-ssh` showing levels
- **TODO** Added `s3d-flow-finish`
- Added `s3d-bash`
- Added checkout of detached head
- Added pre-release id incrementing
- Added push to `next`
- Changed most script names
- Improved `README.md`
- Replaced `LICENSE`

diff --git a/s3d-flow b/s3d-flow
--- a/s3d-flow
+++ b/s3d-flow
@@ -1,6 +1,13 @@
 #!/bin/bash
 set -e
 
+v=$(s3d-flow-json | jq -r .latest)
+v2=$(s3d-flow-json | jq -r .release)
+if [[ "$v" == "$v2" ]]; then
+  echo 'ERROR: Flow not started' >&2
+  exit 1
+fi
+ 
 # Run local flow
 if [[ 's3d-scripts' != "${PWD##*/}" ]]; then
   if [ -e ./s3d-flow ]; then
