0.0.5-01c3 Changes; 9 of 9 completed
- Added `s3d-flow-finish`
- Added `part` output to `s3d-flow-json`
- Added `s3d-bash`
- Added checkout of detached head
- Added pre-release id incrementing
- Added push to `next`
- Changed most script names
- Improved `README.md`
- Replaced `LICENSE`

diff --git a/s3d-flow-check b/s3d-flow-check
--- a/s3d-flow-check
+++ b/s3d-flow-check
@@ -8,7 +8,7 @@ block=$(echo "$block" | grep -v -E '^##')
 done=$(echo "$block" | grep -v -E '^- \*\*TODO\*\*' | wc -l)
 items=$(echo "$block" | grep -E '^-' | wc -l)
 
-if [[ done != items ]]; then
-  echo 'ERROR: not all items are done!' >&2
+if [[ $done != $items ]]; then
+  echo "ERROR: not all items are done!" >&2
   exit 1
 fi
